# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sFanrfHCObOaFG9-pL42Jhp6RR9L0fE1
"""

import streamlit as st
import pandas as pd
import seaborn as sns

st.title('Analyse de corrélation et de distribution de la base de données "cars"')

link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
df_voiture = pd.read_csv(link)


st.title("Tableau complet")

df_voiture

st.title("Sélection par continent")

Continents = st.radio(
     "Continent",
     ('US', 'Euope', 'Japan'))

if Continents == 'US':
    st.write('You selected US.')
    df_voiture[df_voiture["continent"].str.contains('US.')]
elif Continents == 'Euope':
    st.write('You selected Euope.')
    df_voiture[df_voiture["continent"].str.contains('Europe.')]
elif Continents == 'Japan':
    st.write('You selected Japan.')
    df_voiture[df_voiture["continent"].str.contains('Japan.')]
else :
    st.write('You selected None.')
    st.write(df_voiture)


"""st.title("Corrélation")

viz_correlation = sns.heatmap(df_voiture.corr(), 
                                center=0,
                                cmap = sns.color_palette("vlag", as_cmap=True),annot=True
                                )
st.pyplot(viz_correlation.figure) 


st.title("Corrélation cylinders/cubicinches")

viz_correlation_cylinders_cubocinches = sns.scatterplot(data=df_voiture, x="cylinders", y="cubicinches", hue="continent")
st.pyplot(viz_correlation_cylinders_cubocinches.figure) """



viz_correlation_line_charts = st.line_chart(df_voiture)
st.pyplot(viz_correlation_line_charts)


